fetch('/includes.html').then(r=>r.text()).then(h=>{document.getElementById('includesGrid').innerHTML=h}).catch(console.error);

const SERVICES=[{"category": "Accesorios y complementos", "name": "Almohadones decorativos", "price": 2000, "unit": "unidad"}, {"category": "Accesorios y complementos", "name": "Almohadones grandes", "price": 4500, "unit": "unidad"}, {"category": "Accesorios y complementos", "name": "Apoya pie", "price": 49999, "unit": "unidad"}, {"category": "Accesorios y complementos", "name": "Pie de cama", "price": 44999, "unit": "unidad"}, {"category": "Accesorios y complementos", "name": "Respaldo y pie de cama", "price": 70000, "unit": "unidad"}, {"category": "Bebés", "name": "Cochecito de bebé", "price": 85000, "unit": "unidad"}, {"category": "Bebés", "name": "Huevito", "price": 55000, "unit": "unidad"}, {"category": "Colchones y sommiers", "name": "Colchón 1 plaza", "price": 70000, "unit": "unidad"}, {"category": "Colchones y sommiers", "name": "Colchón 2 plazas + Sommier", "price": 99999, "unit": "unidad"}, {"category": "Colchones y sommiers", "name": "Colchón de cuna", "price": 54999, "unit": "unidad"}, {"category": "Colchones y sommiers", "name": "Colchón King + Sommier", "price": 119999, "unit": "unidad"}, {"category": "Sillas y sillones", "name": "Sillas", "price": 15000, "unit": "unidad"}, {"category": "Sillas y sillones", "name": "Sillas dobles", "price": 30000, "unit": "unidad"}, {"category": "Sillas y sillones", "name": "Sillón por cuerpo", "price": 49999, "unit": "cuerpo", "special": "sofa"}, {"category": "Superficies textiles", "name": "Alfombra m²", "price": 11500, "unit": "m²"}, {"category": "Superficies textiles", "name": "Cortinas m²", "price": 12500, "unit": "m²"}, {"category": "Vehículos", "name": "Auto estándar", "price": 149999, "unit": "vehículo"}];
const money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Math.round(n)).replace('ARS','$');
const rows=document.getElementById('serviceRows');
function serviceOptions(selected=''){let out='<option value="">Seleccionar servicio</option>';let cat='';SERVICES.forEach((s,i)=>{if(s.category!==cat){if(cat)out+='</optgroup>';cat=s.category;out+=`<optgroup label="${cat}">`}out+=`<option value="${i}" ${String(i)===String(selected)?'selected':''}>${s.name}</option>`});return out+'</optgroup>'}
function addRow(sel='',qty=1){const div=document.createElement('div');div.className='service-row';div.innerHTML=`<div><label>Servicio</label><select class="srv">${serviceOptions(sel)}</select></div><div><label>Cantidad</label><input class="qty" type="number" min="1" step="1" value="${qty}"></div><button class="remove">×</button>`;div.querySelector('.remove').onclick=()=>{div.remove();update()};div.querySelectorAll('select,input').forEach(x=>x.addEventListener('input',update));rows.appendChild(div);update()}
function calcLine(s,q){if(s.special==='sofa')return q<=3?q*50000:3*50000+(q-3)*30000;return s.price*q}
function rowHtml(items,discount=0,includeHeader=true,minRows=0){let html=includeHeader?'<div class="m-row m-th"><div>SERVICIO</div><div>CANT.</div><div>P. UNIT.</div><div>SUBTOTAL</div></div>':'';items.forEach(x=>{const unit=x.s.special==='sofa'?(x.q===1?'1 cuerpo':`${x.q} cuerpos`):`${x.q} ${x.s.unit==='m²'?'m²':'u.'}`;const pu=x.s.special==='sofa'?(x.q<=3?50000:Math.round(x.sub/x.q)):x.s.price;html+=`<div class="m-row"><div>${x.s.name}</div><div class="center">${unit}</div><div class="right">${money(pu)}</div><div class="right">${money(x.sub)}</div></div>`});for(let i=items.length;i<minRows;i++){html+='<div class="m-row empty"><div>&nbsp;</div><div>&nbsp;</div><div>&nbsp;</div><div>&nbsp;</div></div>'}if(discount>0)html+=`<div class="m-row disc"><div>${discName.value||'Descuento especial'}</div><div></div><div></div><div class="right">- ${money(discount)}</div></div>`;return html}
function update(){const d=date.value;const formatted=d?d.split('-').reverse().join('/'):'—';p1Date.textContent=formatted;p1Client.textContent=(client.value||'—').toUpperCase();p1Zone.textContent=(zone.value||'—').toUpperCase();let items=[];document.querySelectorAll('.service-row').forEach(r=>{const idx=r.querySelector('.srv').value,q=Number(r.querySelector('.qty').value)||0;if(idx!==''&&q>0){const s=SERVICES[idx],sub=calcLine(s,q);items.push({s,q,sub})}});let base=items.reduce((a,x)=>a+x.sub,0),discount=0;if(discType.value==='percent')discount=base*(Number(discValue.value)||0)/100;if(discType.value==='amount')discount=Math.min(base,Number(discValue.value)||0);const total=Math.max(0,base-discount),quota=total*1.30/3;const first=items.slice(0,3),rest=items.slice(3);p1Table.innerHTML=rowHtml(first,rest.length?0:discount,true,3);continueText.style.display=rest.length?'block':'none';moreWrap.style.display=rest.length?'block':'none';p2Table.innerHTML=rest.length?rowHtml(rest,discount,true,0):'';p1Total.textContent=money(total);p1Cash.textContent=money(total);p1Card.textContent=`3 × ${money(quota)}`;scalePages()}
['client','zone','date','discType','discValue','discName'].forEach(id=>document.getElementById(id).addEventListener('input',update));addService.onclick=()=>addRow();
function fileName(){const safe=(client.value||'Cliente').trim().replace(/[^a-zA-Z0-9áéíóúÁÉÍÓÚñÑ_-]+/g,'-').replace(/-+/g,'-');return `Cotizacion-Cleaning-${safe||'Cliente'}.pdf`}
async function capturePage(source){const host=document.createElement('div');Object.assign(host.style,{position:'fixed',left:'-10000px',top:'0',width:'540px',height:'960px',background:'#fff',zIndex:'-9999'});const clone=source.cloneNode(true);Object.assign(clone.style,{width:'540px',height:'960px',margin:'0',transform:'none',boxShadow:'none'});host.appendChild(clone);document.body.appendChild(host);try{if(document.fonts&&document.fonts.ready)await document.fonts.ready;await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return await html2canvas(clone,{scale:2,useCORS:true,backgroundColor:'#fff',width:540,height:960,windowWidth:540,windowHeight:960,scrollX:0,scrollY:0,logging:false})}finally{host.remove()}}
async function buildPDF(){update();const c1=await capturePage(page1);const c2=await capturePage(page2);const {jsPDF}=window.jspdf;const pdf=new jsPDF({orientation:'portrait',unit:'mm',format:[108,192],compress:true});pdf.addImage(c1.toDataURL('image/jpeg',.96),'JPEG',0,0,108,192,undefined,'FAST');pdf.addPage([108,192],'portrait');pdf.addImage(c2.toDataURL('image/jpeg',.96),'JPEG',0,0,108,192,undefined,'FAST');return pdf}
async function sharePDF(){shareBtn.disabled=true;shareBtn.textContent='Preparando PDF...';try{const pdf=await buildPDF();const file=new File([pdf.output('blob')],fileName(),{type:'application/pdf'});const data={files:[file],title:'Cotización Cleaning Services'};if(navigator.share&&(!navigator.canShare||navigator.canShare(data))){await navigator.share(data)}else{alert('Este dispositivo no permite compartir archivos directamente. Usá el botón Descargar PDF.')}}catch(e){if(e&&e.name!=='AbortError'){console.error(e);alert('No se pudo compartir el PDF.')}}finally{shareBtn.disabled=false;shareBtn.textContent='Compartir PDF'}}
async function downloadPDF(){pdfBtn.disabled=true;pdfBtn.textContent='Generando PDF...';try{const pdf=await buildPDF();pdf.save(fileName())}catch(e){console.error(e);alert('No se pudo descargar el PDF.')}finally{pdfBtn.disabled=false;pdfBtn.textContent='Descargar PDF'}}
shareBtn.onclick=sharePDF;
pdfBtn.onclick=downloadPDF;
function scalePages(){document.querySelectorAll('.page-slot').forEach(slot=>{const scaler=slot.querySelector('.page-scaler');const available=Math.min(540,Math.max(280,document.querySelector('.preview-wrap').clientWidth-24));const scale=available/540;scaler.style.transform=`scale(${scale})`;slot.style.width=(540*scale)+'px';slot.style.height=(960*scale)+'px'})}
window.addEventListener('resize',scalePages);date.value=new Date().toISOString().slice(0,10);update();setTimeout(scalePages,50);

if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => navigator.serviceWorker.register('/service-worker.js').catch(console.error));
}
